import { tool } from 'ai';
import { z } from 'zod';
import { SandboxService } from '../../sandbox/sandbox.service.js';
import { McpService } from '../../mcp/mcp.service.js';
import {
  patchNextConfig,
  patchRootLayout,
  generateI18nConfig,
  generateI18nProvider,
  generateLanguageSwitcher,
  generateTextTranslator,
} from '../../common/utils/file-patcher.js';
import type { EmitFn } from '../../common/types/index.js';

const inputSchema = z.object({
  sandboxId: z.string().describe('E2B sandbox ID'),
  workDir: z.string().describe('Absolute path to the cloned repo'),
  framework: z.string().describe('Framework identifier, e.g. nextjs-app-router'),
  locales: z.array(z.string()).describe('Target locale codes, e.g. ["fr", "ar", "ja"]'),
  layoutPath: z.string().describe('Absolute path to root layout file'),
  nextConfigPath: z.string().describe('Absolute path to next.config file'),
});

/**
 * Tool 4 — setup_lingo:
 *
 * Self-contained custom i18n runtime — zero external npm deps, zero sandbox installs.
 * Translations are served from public/locales/<locale>.json (generated by install_and_translate).
 * Runtime: LanguageProvider (React context) + TextTranslator (DOM walker) + LanguageSwitcher.
 *
 * Why NOT @lingo.dev/compiler:
 *   @lingo.dev/compiler@latest has a packaging bug: the webpack plugin file
 *   `build/plugin/index.cjs` is missing from the npm publish → Next.js build fails.
 *   The correct approach is our custom runtime, which has zero external deps.
 */
export function createSetupLingoTool(sandbox: SandboxService, mcp: McpService, emit: EmitFn) {
  return tool({
    description:
      'Writes a self-contained i18n runtime (LanguageProvider + TextTranslator + LanguageSwitcher) ' +
      'into the target repo. Zero external npm deps. Translations loaded from public/locales/*.json ' +
      'at runtime, which are generated by install_and_translate using Babel AST extraction + Lingo.dev SDK.',
    inputSchema,
    execute: async ({ sandboxId, workDir, framework, locales, layoutPath, nextConfigPath }) => {
      emit({ level: 'info', message: 'Configuring i18n runtime…', timestamp: new Date(), step: 'setup_lingo' });

      if (mcp.isConnected) {
        try {
          await mcp.getSetupInstructions(framework, locales);
        } catch { /* non-fatal */ }
      }

      const modifiedFiles: string[] = [];

      // 1. Write i18n.json (locale config read by install_and_translate)
      await sandbox.writeFile(sandboxId, `${workDir}/i18n.json`, generateI18nConfig('en', locales));
      modifiedFiles.push(`${workDir}/i18n.json`);
      emit({ level: 'info', message: 'Written i18n.json', timestamp: new Date(), step: 'setup_lingo' });

      // 2. No-op: custom runtime doesn't touch next.config
      const nextConfigContent = await sandbox.readFile(sandboxId, nextConfigPath);
      await sandbox.writeFile(sandboxId, nextConfigPath, patchNextConfig(nextConfigContent));
      modifiedFiles.push(nextConfigPath);

      // 3. Write runtime files — i18n/ sibling to layout.tsx so relative imports resolve
      const layoutDir = layoutPath.substring(0, layoutPath.lastIndexOf('/'));
      await sandbox.exec(sandboxId, `mkdir -p ${layoutDir}/i18n`);

      const providerPath = `${layoutDir}/i18n/provider.tsx`;
      const switcherPath = `${layoutDir}/i18n/switcher.tsx`;
      const translatorPath = `${layoutDir}/i18n/text-translator.tsx`;

      await sandbox.writeFile(sandboxId, providerPath, generateI18nProvider());
      await sandbox.writeFile(sandboxId, switcherPath, generateLanguageSwitcher());
      await sandbox.writeFile(sandboxId, translatorPath, generateTextTranslator());
      modifiedFiles.push(providerPath, switcherPath, translatorPath);
      emit({
        level: 'info',
        message: 'Written LanguageProvider + LanguageSwitcher + TextTranslator',
        timestamp: new Date(),
        step: 'setup_lingo',
      });

      // 4. Inject LanguageProvider + TextTranslator + LanguageSwitcher into root layout
      const layoutContent = await sandbox.readFile(sandboxId, layoutPath);
      await sandbox.writeFile(sandboxId, layoutPath, patchRootLayout(layoutContent, locales));
      modifiedFiles.push(layoutPath);
      emit({
        level: 'info',
        message: `Patched ${layoutPath} with LanguageProvider`,
        timestamp: new Date(),
        step: 'setup_lingo',
      });

      emit({
        level: 'success',
        message: `i18n runtime configured — ${modifiedFiles.length} files written`,
        timestamp: new Date(),
        step: 'setup_lingo',
      });

      return { modifiedFiles, runtimeStrategy: 'custom' };
    },
  });
}
